import type {
  ProductCard,
  ProductDetailData,
} from "@/entities/product/model/types"

/** 상품목록(C-01)에 노출되는 정기예금·정기적금 카드. */
export const MOCK_PRODUCTS: ProductCard[] = [
  {
    id: "P001",
    category: "정기예금",
    name: "코어 정기예금",
    summary: "여윳돈을 안전하게 굴리는 기본 정기예금입니다.",
    maxRate: 3.85,
    baseRate: 3.1,
    period: "6개월 ~ 36개월",
    minAmount: 100_000,
    maxAmount: 500_000_000,
    updatedAt: "2026-07-20",
  },
  {
    id: "P002",
    category: "정기적금",
    name: "코어 자유적금",
    summary: "매달 원하는 금액을 자유롭게 납입하는 적금입니다.",
    maxRate: 4.2,
    baseRate: 3.7,
    period: "12개월 ~ 36개월",
    minAmount: 10_000,
    maxAmount: 3_000_000,
    updatedAt: "2026-07-25",
  },
  {
    id: "P003",
    category: "정기예금",
    name: "코어 목돈예금",
    summary: "목돈을 장기간 예치할수록 금리가 높아지는 예금입니다.",
    maxRate: 4.05,
    baseRate: 3.5,
    period: "12개월 ~ 60개월",
    minAmount: 1_000_000,
    maxAmount: 1_000_000_000,
    updatedAt: "2026-07-18",
  },
  {
    id: "P004",
    category: "정기적금",
    name: "코어 정기적금",
    summary: "매달 같은 금액을 납입해 만기에 목돈을 만드는 적금입니다.",
    maxRate: 4.35,
    baseRate: 3.8,
    period: "6개월 ~ 24개월",
    minAmount: 50_000,
    maxAmount: 2_000_000,
    updatedAt: "2026-07-22",
  },
  {
    id: "P005",
    category: "정기예금",
    name: "코어 단기예금",
    summary: "짧은 기간 자금을 예치하기 좋은 단기 정기예금입니다.",
    maxRate: 3.4,
    baseRate: 2.6,
    period: "1개월 ~ 12개월",
    minAmount: 500_000,
    maxAmount: 300_000_000,
    updatedAt: "2026-07-15",
  },
  {
    id: "P006",
    category: "정기적금",
    name: "코어 목표적금",
    summary: "목표 금액을 정해 꾸준히 모으는 정기적금입니다.",
    maxRate: 4.5,
    baseRate: 3.95,
    period: "12개월 ~ 36개월",
    minAmount: 30_000,
    maxAmount: 5_000_000,
    updatedAt: "2026-07-28",
  },
]

const COMMON_NOTICES = [
  "이 상품의 금리는 가입일 기준으로 확정되며, 가입 후 시장금리 변동과 무관하게 유지됩니다.",
  "우대금리는 조건 충족 여부에 따라 적용되며, 조건 미충족 시 기본금리만 적용됩니다.",
  "만기 전 중도해지 시 약정이율보다 낮은 중도해지이율이 적용되어 이자가 줄어듭니다.",
  "세금은 관련 세법에 따라 부과되며, 표시된 금리는 세전 기준입니다.",
]

/** 상품상세(C-02) 데이터. 상품목록(C-01)의 id 별로 조회한다. */
export const MOCK_PRODUCT_DETAILS: Record<string, ProductDetailData> = {
  P001: {
    id: "P001",
    category: "정기예금",
    name: "코어 정기예금",
    summary: "여윳돈을 안전하게 굴리는 기본 정기예금입니다.",
    maxRate: 3.85,
    period: "6개월 ~ 36개월",
    minAmount: 100_000,
    maxAmount: 500_000_000,
    interestMethod: "만기일시지급식",
    guide: [
      { label: "가입대상", value: "실명의 개인 및 개인사업자 (1인 1계좌)" },
      { label: "가입기간", value: "6개월 이상 36개월 이하 (월 단위 선택)" },
      { label: "가입금액", value: "최소 100,000원 이상, 최대 5억원 이하" },
      {
        label: "이자지급시기",
        value: "만기일에 원금과 이자를 함께 지급합니다.",
      },
      {
        label: "중도해지",
        value: "만기 전 해지 시 중도해지이율이 적용됩니다.",
      },
    ],
    rates: [
      { period: "6개월", baseRate: 3.1, primeRate: 0.25, maxRate: 3.35 },
      { period: "12개월", baseRate: 3.45, primeRate: 0.3, maxRate: 3.75 },
      { period: "24개월", baseRate: 3.55, primeRate: 0.3, maxRate: 3.85 },
      { period: "36개월", baseRate: 3.6, primeRate: 0.25, maxRate: 3.85 },
    ],
    notices: COMMON_NOTICES,
  },
  P002: {
    id: "P002",
    category: "정기적금",
    name: "코어 자유적금",
    summary: "매달 원하는 금액을 자유롭게 납입하는 적금입니다.",
    maxRate: 4.2,
    period: "12개월 ~ 36개월",
    minAmount: 10_000,
    maxAmount: 3_000_000,
    interestMethod: "만기일시지급식",
    guide: [
      { label: "가입대상", value: "실명의 개인 (1인 1계좌)" },
      { label: "가입기간", value: "12개월 이상 36개월 이하 (월 단위 선택)" },
      {
        label: "가입금액",
        value: "매월 10,000원 이상, 3,000,000원 이하 자유 납입",
      },
      {
        label: "이자지급시기",
        value: "만기일에 원금과 이자를 함께 지급합니다.",
      },
      {
        label: "중도해지",
        value: "만기 전 해지 시 중도해지이율이 적용됩니다.",
      },
    ],
    rates: [
      { period: "12개월", baseRate: 3.7, primeRate: 0.4, maxRate: 4.1 },
      { period: "24개월", baseRate: 3.85, primeRate: 0.35, maxRate: 4.2 },
      { period: "36개월", baseRate: 3.9, primeRate: 0.3, maxRate: 4.2 },
    ],
    notices: COMMON_NOTICES,
  },
  P003: {
    id: "P003",
    category: "정기예금",
    name: "코어 목돈예금",
    summary: "목돈을 장기간 예치할수록 금리가 높아지는 예금입니다.",
    maxRate: 4.05,
    period: "12개월 ~ 60개월",
    minAmount: 1_000_000,
    maxAmount: 1_000_000_000,
    interestMethod: "만기일시지급식",
    guide: [
      { label: "가입대상", value: "실명의 개인 및 개인사업자 (1인 1계좌)" },
      { label: "가입기간", value: "12개월 이상 60개월 이하 (월 단위 선택)" },
      { label: "가입금액", value: "최소 1,000,000원 이상, 최대 10억원 이하" },
      {
        label: "이자지급시기",
        value: "만기일에 원금과 이자를 함께 지급합니다.",
      },
      {
        label: "중도해지",
        value: "만기 전 해지 시 중도해지이율이 적용됩니다.",
      },
    ],
    rates: [
      { period: "12개월", baseRate: 3.5, primeRate: 0.3, maxRate: 3.8 },
      { period: "24개월", baseRate: 3.65, primeRate: 0.3, maxRate: 3.95 },
      { period: "36개월", baseRate: 3.7, primeRate: 0.3, maxRate: 4.0 },
      { period: "60개월", baseRate: 3.75, primeRate: 0.3, maxRate: 4.05 },
    ],
    notices: COMMON_NOTICES,
  },
  P004: {
    id: "P004",
    category: "정기적금",
    name: "코어 정기적금",
    summary: "매달 같은 금액을 납입해 만기에 목돈을 만드는 적금입니다.",
    maxRate: 4.35,
    period: "6개월 ~ 24개월",
    minAmount: 50_000,
    maxAmount: 2_000_000,
    interestMethod: "만기일시지급식",
    guide: [
      { label: "가입대상", value: "실명의 개인 (1인 1계좌)" },
      { label: "가입기간", value: "6개월 이상 24개월 이하 (월 단위 선택)" },
      {
        label: "가입금액",
        value: "매월 50,000원 이상, 2,000,000원 이하 정액 납입",
      },
      {
        label: "이자지급시기",
        value: "만기일에 원금과 이자를 함께 지급합니다.",
      },
      {
        label: "중도해지",
        value: "만기 전 해지 시 중도해지이율이 적용됩니다.",
      },
    ],
    rates: [
      { period: "6개월", baseRate: 3.8, primeRate: 0.4, maxRate: 4.2 },
      { period: "12개월", baseRate: 3.95, primeRate: 0.4, maxRate: 4.35 },
      { period: "24개월", baseRate: 3.9, primeRate: 0.35, maxRate: 4.25 },
    ],
    notices: COMMON_NOTICES,
  },
  P005: {
    id: "P005",
    category: "정기예금",
    name: "코어 단기예금",
    summary: "짧은 기간 자금을 예치하기 좋은 단기 정기예금입니다.",
    maxRate: 3.4,
    period: "1개월 ~ 12개월",
    minAmount: 500_000,
    maxAmount: 300_000_000,
    interestMethod: "만기일시지급식",
    guide: [
      { label: "가입대상", value: "실명의 개인 및 개인사업자 (1인 1계좌)" },
      { label: "가입기간", value: "1개월 이상 12개월 이하 (월 단위 선택)" },
      { label: "가입금액", value: "최소 500,000원 이상, 최대 3억원 이하" },
      {
        label: "이자지급시기",
        value: "만기일에 원금과 이자를 함께 지급합니다.",
      },
      {
        label: "중도해지",
        value: "만기 전 해지 시 중도해지이율이 적용됩니다.",
      },
    ],
    rates: [
      { period: "1개월", baseRate: 2.6, primeRate: 0.1, maxRate: 2.7 },
      { period: "3개월", baseRate: 2.85, primeRate: 0.15, maxRate: 3.0 },
      { period: "6개월", baseRate: 3.05, primeRate: 0.2, maxRate: 3.25 },
      { period: "12개월", baseRate: 3.15, primeRate: 0.25, maxRate: 3.4 },
    ],
    notices: COMMON_NOTICES,
  },
  P006: {
    id: "P006",
    category: "정기적금",
    name: "코어 목표적금",
    summary: "목표 금액을 정해 꾸준히 모으는 정기적금입니다.",
    maxRate: 4.5,
    period: "12개월 ~ 36개월",
    minAmount: 30_000,
    maxAmount: 5_000_000,
    interestMethod: "만기일시지급식",
    guide: [
      { label: "가입대상", value: "실명의 개인 (1인 1계좌)" },
      { label: "가입기간", value: "12개월 이상 36개월 이하 (월 단위 선택)" },
      {
        label: "가입금액",
        value: "매월 30,000원 이상, 5,000,000원 이하 정액 납입",
      },
      {
        label: "이자지급시기",
        value: "만기일에 원금과 이자를 함께 지급합니다.",
      },
      {
        label: "중도해지",
        value: "만기 전 해지 시 중도해지이율이 적용됩니다.",
      },
    ],
    rates: [
      { period: "12개월", baseRate: 3.95, primeRate: 0.45, maxRate: 4.4 },
      { period: "24개월", baseRate: 4.0, primeRate: 0.45, maxRate: 4.45 },
      { period: "36개월", baseRate: 4.05, primeRate: 0.45, maxRate: 4.5 },
    ],
    notices: COMMON_NOTICES,
  },
}
